[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:api]
command=node /opt/sala200-api/server.js
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:netplay]
command=node /opt/netplay/index.js
directory=/opt/netplay
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:catalogo]
command=/bin/sh -c "while true; do python3 /opt/sala200/genlist.py >/dev/null 2>&1; sleep 600; done"
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
